// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1F3F8p0pCK9_ZBYi7RPNmnuXM5RAgnVU',
    appId: '1:124144794866:web:136e3a5877685e413ca46b',
    messagingSenderId: '124144794866',
    projectId: 'spark-22125',
    authDomain: 'spark-22125.firebaseapp.com',
    databaseURL: 'https://spark-22125-default-rtdb.firebaseio.com',
    storageBucket: 'spark-22125.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANA-k7Cy0yWZNVvC3zJ__Cqez_yIETwWM',
    appId: '1:124144794866:android:8ef586687ea5943e3ca46b',
    messagingSenderId: '124144794866',
    projectId: 'spark-22125',
    databaseURL: 'https://spark-22125-default-rtdb.firebaseio.com',
    storageBucket: 'spark-22125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBageyMBIY8pVCt4tMXReUfoa2Q4zP91-E',
    appId: '1:124144794866:ios:cfca0f8ac6a197b73ca46b',
    messagingSenderId: '124144794866',
    projectId: 'spark-22125',
    databaseURL: 'https://spark-22125-default-rtdb.firebaseio.com',
    storageBucket: 'spark-22125.appspot.com',
    iosClientId: '124144794866-0t9mlsfvle2l7lmm9dkadapt9am1hgoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBageyMBIY8pVCt4tMXReUfoa2Q4zP91-E',
    appId: '1:124144794866:ios:cfca0f8ac6a197b73ca46b',
    messagingSenderId: '124144794866',
    projectId: 'spark-22125',
    databaseURL: 'https://spark-22125-default-rtdb.firebaseio.com',
    storageBucket: 'spark-22125.appspot.com',
    iosClientId: '124144794866-0t9mlsfvle2l7lmm9dkadapt9am1hgoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );
}
